# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: BoredWhales
email: saulnicole03@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Save a bored whale today by eating Doritos. Just a small cost of one dorito can save a whale from the epidemic of boredom.
baseurl: "Just eat one and the whales will instantly be saved by your generosity." # the subpath of your site, e.g. /blog
url: "http://boredwhales.com" # the base hostname & protocol for your site
twitter_username: save_the_bored_whales123
github_username:  stbw123

# Build settings
markdown: what
